module.exports = [
  //   "/algorithm/",
  "Java.md",
  "01_an_introduction_to_java.md",
  "02_the_java_programming_environment.md",
  "03_fundamental_programming_structures_in_java_00_comments.md",
  "04_fundamental_programming_structures_in_java_01_data_types_and_variables.md",
  "05_fundamental_programming_structures_in_java_02_operators.md",
  "06_fundamental_programming_structures_in_java_03_strings.md",
  "07_fundamental_programming_structures_in_java_04_input_and_output.md",
  "08_fundamental_programming_structures_in_java_05_control_flow.md",
  "09_fundamental_programming_structures_in_java_06_big_numbers.md",
  "10_fundamental_programming_structures_in_java_07_arrays.md",
  "11_java_ide_intellij_idea.md",
  "12_objects_and_classes_00_introduction_to_object-oriented_programming.md",
  "13_objects_and_classes_01_using_predefined_classes.md",
  "14_objects_and_classes_02_defining_your_own_classes.md",
  "15_objects_and_classes_03_static_fileds_and_methods.md",
  "16_objects_and_classes_04_method_parameters.md",
  "17_objects_and_classes_05_object_construction.md",
  "18_objects_and_classes_06_packages.md",
  "19_objects_and_classes_07_the_class_path.md",
  "20_objects_and_classes_08_documentation_comments.md",
  "21_objects_and_classes_09class_design_hints.md",
];
