name: Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@main
        with:
          actions: "add-assignees"
          token: ${{ secrets.RYAN_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: "Ryanjiena"
          random-to: 1
