name: Add Labels

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'xxx') == false
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@main
        with:
          actions: "add-labels"
          token: ${{ secrets.RYAN_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "😄 to do,documentation,in-progress,priority-2"
