name: Issue Month Statistics

on:
  schedule:
    - cron: "0 1 1 * *"

jobs:
  month-statistics:
    runs-on: ubuntu-latest
    steps:
      - name: month-statistics
        uses: actions-cool/issues-helper@main
        with:
          actions: "month-statistics"
          token: ${{ secrets.RYAN_TOKEN }}
          lables: "statistics"
          count-lables: "true"
          count-comments: "true"
          assignees: "Ryanjiena"
